### ISSUE TITLE
Release Checklist v0.2.0

### ISSUE THREAD

**Issue by rkistner** [powersync-ja/powersync-sqlite-core#23]
This is a checklist to track the release of v0.2.0.

Changes:
 * Sync optimizations - #19
 * Add `powersync_client_id()` / `powersync_last_synced_at()` / `powersync_clear()` - #21

Core builds:
 * [x] Release PR: #22.
 * [x] Release: [v0.2.0](https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.2.0)
 * [x] Android aar released on Maven Central
 * [x] Cocoapod released
 * [x] wa-sqlite build - Released as 0.3.0 - https://github.com/powersync-ja/wa-sqlite/pull/12 / https://github.com/powersync-ja/wa-sqlite/pull/11
 * [x] sqlite3.dart build - Released [v2.4.5-powersync.0.2.0](https://github.com/powersync-ja/sqlite3.dart/releases/tag/v2.4.5-powersync.0.2.0) in https://github.com/powersync-ja/sqlite3.dart/pull/8

Skipping SDK updates, going to v0.2.1 instead:
 * powersync.dart
 * powersync-js - web
 * react-native-quick-sqlite
 * powersync-js - react native
 * kotlin
 * swift
