### ISSUE TITLE
Release checklist v0.2.1

### ISSUE THREAD

**Issue by rkistner** [powersync-ja/powersync-sqlite-core#25]
This is a checklist to track the release of v0.2.1.

Changes:
 * Prefab build for android - #24 (not relevant for most client SDKs)

Core builds:
 * [x] Release PR: #24.
 * [x] Release: [v0.2.1](https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.2.1)
 * [x] Android aar released on Maven Central
 * [x] Cocoapod released
 * [x] react-native-quick-sqlite - v1.3.0 - https://github.com/powersync-ja/react-native-quick-sqlite/pull/40
 * [x] wa-sqlite build - skipping
 * [x] sqlite3.dart build - skipping

SDK updates:
 * [x] powersync.dart - v1.8.1 - https://github.com/powersync-ja/powersync.dart/pull/148
 * [x] powersync-js - web - https://github.com/powersync-ja/powersync-js/pull/289
 * [x] powersync-js - react native - https://github.com/powersync-ja/powersync-js/pull/289
 * [x] kotlin
 * [x] swift
