### ISSUE TITLE
Release Checklist v0.3.0

### ISSUE THREAD

**Issue by rkistner** [powersync-ja/powersync-sqlite-core#33]
This is a checklist to track the release of v0.3.0.

Changes:
 * #26 (speeds up incremental sync)
 * #27 / #30 (further speeds up incremental sync)
 * #28 (to support sqlcipher)

Core builds:
 * [x] Release PR: #29.
 * [x] GitHub Release - https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.3.0
 * [x] Android aar released on Maven Central
 * [x] Cocoapod released
 * [x] react-native-quick-sqlite - https://github.com/powersync-ja/react-native-quick-sqlite/pull/51 / https://github.com/powersync-ja/react-native-quick-sqlite/pull/52 - `@journeyapps/react-native-quick-sqlite@2.0.0`
 * [x] wa-sqlite build - https://github.com/powersync-ja/wa-sqlite/pull/14 / https://github.com/powersync-ja/wa-sqlite/pull/15 - `@journeyapps/wa-sqlite@0.4.0`
 * [x] sqlite3.dart build - https://github.com/powersync-ja/sqlite3.dart/pull/9

SDK updates:
 * [x] powersync.dart - https://github.com/powersync-ja/powersync.dart/pull/185 / https://github.com/powersync-ja/powersync.dart/pull/188 `powersync_flutter_libs@0.4.0` / `powersync@1.8.5`
 * [x] powersync-js - web & react-native & op-sqlite - https://github.com/powersync-ja/powersync-js/pull/334 / https://github.com/powersync-ja/powersync-js/pull/341 / https://github.com/powersync-ja/powersync-js/pull/343 - `@powersync/react-native@1.14.0` / `@powersync/web@1.9.0` / `@powersync/op-sqlite@0.0.2`
 * [x] kotlin & swift - https://github.com/powersync-ja/powersync-kotlin/pull/67 / https://github.com/powersync-ja/powersync-kotlin/pull/68 - `1.0.0-BETA3`
