### ISSUE TITLE
Release Checklist v0.3.6

### ISSUE THREAD

**Issue by rkistner** [powersync-ja/powersync-sqlite-core#47]
This is a checklist to track the release of v0.3.6.

Changes:
 * #45 Fix issue with remove operations resulting in dangling rows in some cases
 * #46 Removing dangling rows previously caused by the above issue

Note: v0.3.5 already contains #45, but was not released to all SDKs.

Core builds:
 * [x] Release PR: #46.
 * [x] GitHub Release - https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.3.6
 * [x] Android aar released on Maven Central
 * [x] Cocoapod released
 * [x] react-native-quick-sqlite - https://github.com/powersync-ja/react-native-quick-sqlite/pull/62 / https://github.com/powersync-ja/react-native-quick-sqlite/pull/63 - v2.1.2
 * [x] wa-sqlite build - https://github.com/powersync-ja/wa-sqlite/pull/20 / https://github.com/powersync-ja/wa-sqlite/pull/21 - v0.4.2
 * [x] sqlite3.dart build - https://github.com/powersync-ja/sqlite3.dart/pull/15

SDK updates:
 * [x] powersync.dart - https://github.com/powersync-ja/powersync.dart/pull/211 - powersync 1.9.3 / powersync_flutter_libs 0.4.3
 * [x] powersync-js - web & react-native & op-sqlite - https://github.com/powersync-ja/powersync-js/pull/395 / https://github.com/powersync-ja/powersync-js/pull/396 - `@powersync/react-native@1.15.1` / `@powersync/web@1.10.2` / `@powersync/op-sqlite@0.1.1`
 * [x] kotlin & swift - https://github.com/powersync-ja/powersync-kotlin/pull/78
